name: tyon
description: TYON (Typed Object Notation) parser
version: 1.0.0
repository: https://github.com/sma/dart_tyon

environment:
  sdk: '>=2.19.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  tyon:
