name: tyon
description: Decodes documents in the TYON (Typed Object Notation) format.
version: 1.0.0+1
repository: https://github.com/sma/dart_tyon

environment:
  sdk: '>=2.19.0 <4.0.0'

dev_dependencies:
  coverage: ^1.6.3
  lints: ^2.0.0
  test: ^1.21.0

executables:
  tyon:
